### ISSUE TITLE
Merge Contact Us and Map Section

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#10]
- Merge the contents of the two sections. 
- Decide if map can go in the background or needs to be changed into a small box on the side. Keep into mind the responsive behavior of the website.
- Design suggested by the OC:
  ![screenshot from 2016-07-02 01-47-58](https://cloud.githubusercontent.com/assets/952036/16533545/1c530c42-3ff7-11e6-9e01-c0e2897255e1.png)
- You have the liberty to think about the design and how it should look as long it works on both mobile and web.
- Ask for any resources like logo, images etc that may be required.

**Comment by ghost** [comment]
Okk...I didn't read this earlier....
Will do it as required !

**Comment by ghost** [comment]
Done !!!
![screenshot from 2016-07-02 17-26-01](https://cloud.githubusercontent.com/assets/16652667/16540221/34ac16fc-407a-11e6-8b14-8d65f966be5b.png)

**Comment by rhnvrm** [comment]
@harshitbudhraja: This is bootstrap so you could maybe use columns and it will automatically do the responsiveness part for you.

**Comment by rhnvrm** [comment]
Use the new emails: admin@snu-breeze.com,
presider@snu-breeze.com,
director@snu-breeze.com,
chair@snu-breeze.com,
sponsorship@snu-breeze.com

**Comment by rhnvrm** [comment]
For now, let's just leave it as it is. I've added a table in the contact section.
