### ISSUE TITLE
Add "Previous Performers" section

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#12]
The main highlight of Breeze has always been the Artists who perform on stage.

This is a very important section and would require photoshop skills to make this section look nice.
- Design how it would look
- Implement it in HTML CSS
- Highlight the big ones and make it interactive

Two possible ways to go about it:
- Implement a slider having graphics sliding through in certain intervals
- Photoshop an image of the artist and on hover show details about them

The design and implementation is up to you.

You can find the past performers here:
[Breeze- Past Performers.docx](https://github.com/rhnvrm/breeze-website/files/344132/Breeze-.Past.Performers.docx)

For any other information or content that may be required ping us here or on email.

**Comment by FlameFractal** [comment]
Hey, what kind of details do we want to show except the names provided in the docx ?
Maybe the year they performed? 
Anyone, any ideas?

Also, wouldn't it be better if we had pictures of them performing live in the breeze and not some random image?

**Comment by FlameFractal** [comment]
https://flamefractal.github.io/breeze-website/

Check the previous performers section. And suggest.

**Comment by Sarthak-Mittal** [comment]
Just for the sake of usability, don't you think the scroll down btn (which takes user to next section) should be visible.
Like instead of giving 100% width to video, if you want to adjust it a little bit so scroll btn is visible even when the user lands on theme section. Same goes for previous performers section.

See this (http://rhnvrm.github.io/breeze-website/ ) just for intuition, look how going from 'logo' section to 'about us' section looks like.

I think it will be much more comfortable in terms of usability! :smile:

**Comment by FlameFractal** [comment]
I did that so the user gets immersive experience while watching the video, without switching to fullscreen.
I can change it, haven't yet sent the PR for this reason only.

Guys, vote? Video 100% size or no?

**Comment by rhnvrm** [comment]
:+1: on @Sarthak-Mittal's suggestion, also there is a modestbranding option that you might want to add to the video so that the youtube logo does not appear. The whole video is copyright infringement according to me.

@FlameFractal Regarding the photos, just consider these as stock photos provided by the content team right now. I'll ask the content team for more photos.

**Comment by FlameFractal** [comment]
Removed arrows except top and bottom ✔️ 
Modestbranding and showinfo = 0✔️ 
Adjusted size of the player (if anyone wants to change this again, feel free to do so!) ✔️
