### ISSUE TITLE
Add a Image Gallery

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#13]
- Add an image gallery that should look good and feel similar to the current theme.
- Selected photos from the past three Breeze Editions will be provided to you.
- It should have features so that it appears interactive, i.e. on hovering should have some text.

**Comment by samin-batra** [comment]
I'll be needing the images for the gallery.

**Comment by rhnvrm** [comment]
@samin-batra Please use stock images for now, i'll send a request for that we might get them by tomorrow.

**Comment by rhnvrm** [comment]
@samin-batra https://www.flickr.com/photos/kondapivskrishnaprasanth

**Comment by Durgaprasad-Nagarkatte** [comment]
As we are creating a page for sponsors, the image of breeze be a slideshow of how much footfall was there, our star performer, and our previous sponsors as they will be interested in that kind of stuff rather than the single countdown page.

**Comment by FlameFractal** [comment]
@samin-batra hey, you done with this? 
I was thinking we could use a cool bootstrap-carousel plugin like owl carousel or something.
What say?

**Comment by Durgaprasad-Nagarkatte** [comment]
How about this one ??
http://www.w3schools.com/howto/default.asp

**Comment by Durgaprasad-Nagarkatte** [comment]
It goes end to end giving the complete feel.

**Comment by samin-batra** [comment]
@FlameFractal, @Durgaprasad-Nagarkatte  I was thinking of a grid like structure, and grouping those images under the events they belong to, i.e breeze '15, '14 and '13, and making them interactive using jquery

**Comment by rhnvrm** [comment]
:+1: Tiles that expand on hovering.

**Comment by samin-batra** [comment]
@rhnvrm could you please specify the problem that was coming in the files that I uploaded earlier?

**Comment by rhnvrm** [comment]
@samin-batra hey sorry for unassigning, actually you had added some commits to the upstream branch without review so that's why I removed your commit access and this un-assignment was done automatically by github.

Also, if you see the pull request you had made, I have mentioned it there as well, in that you have asked to merge the changes in `gh-pages` branch into `master` branch but it should instead be from `your fork's branch` into `gh-pages`

Please send a new PR as I have suggested above ^ :smile:

**Comment by samin-batra** [comment]
ok @rhnvrm i've given a merge request, hopefully now you should be able to see the changes :)

**Comment by rhnvrm** [comment]
@samin-batra @Durgaprasad-Nagarkatte @FlameFractal I've added a responsive flicker embed for now. We can close this issue.
