### ISSUE TITLE
Use Waffle

### ISSUE THREAD

**Issue by mr-karan** [rhnvrm/breeze-website#15]
[Waffle ](https://waffle.io/) can be added for Trello like interface but with stronger Git integration. We used it during the time of _poolyourcar_ development, helped a lot. Issues can be closed from their interface directly, and if in the commit message you write `Fixes/Closes #<issue id>` it automatically moves card to `Done`

(not an issue, feature proposal rather. Feel free to close if not necessary.)

**Comment by rhnvrm** [comment]
:+1:  @mr-karan i'm not savvy with this, i've forgotten how to use it. Please send a mail on the email list explaining how we can use it. https://waffle.io/rhnvrm/breeze-website

**Comment by rhnvrm** [comment]
@FlameFractal please add the badge to the readme in your PR. 
`[![Stories in Ready](https://badge.waffle.io/rhnvrm/breeze-website.png?label=ready&title=Ready)](http://waffle.io/rhnvrm/breeze-website)`

**Comment by FlameFractal** [comment]
done 👍
