### ISSUE TITLE
Make a pre-loader for the website

### ISSUE THREAD

**Issue by ghost** [rhnvrm/breeze-website#19]
We need to make a preloader for the website. 
- One of the design would be the same remote logo of the website spinning till the webpage is rendered, just like it does on the landing page.
- Second option that I think, can be - Joystick buttons randomly pressing on our Breeze '16 logo.

If anyone has any other ideas, we can discuss it here !
P.S. If this issue is not relevant enough, it can be closed :)

**Comment by FlameFractal** [comment]
Wouldn't splash screen be useful if we had large resources to d/l in the bg? 
Otherwise it would just make our site appear slow to load. Just my 2 cents on it.
What does everyone else feel?

**Comment by ghost** [comment]
@FlameFractal , that's a good idea...But, don't you think loading a splash screen with a heavy image would also be slow ?

**Comment by rhnvrm** [comment]
@FlameFractal +1

@harshitbudhraja We will implement a cool loader and splash screen for the Phase 2 website, currently we need a fast loading, mobile friendly responsive Single Page website.

Closing this for now.

**Comment by ghost** [comment]
Sure :) @rhnvrm
