### ISSUE TITLE
Improve About Section

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#20]
@Sarthak-Mittal had added the About section in #18 but we might need to improve it.
- Reduce the font size so that it fits inside the screen atleast for 1024x768
- ~~Try to make the paragraph justified rather than centered so it looks cleaner~~ **DONE**

![rhnvrm github io-breeze-website-](https://cloud.githubusercontent.com/assets/952036/16541052/ad2c812c-4096-11e6-883c-e6d9253504c5.png)
- Try adding some background image from the fest with black-and-white and see if it looks good. (I'll ask the content team if they can provide any images)
- Instead of `About Shiv Nadar University` use `Learn more About Shiv Nadar University`. If it looks decent we can also use an underline if it looks good. This is because it does not look like a link ATM.

**Comment by Sarthak-Mittal** [comment]
Cool, I will work on all of the required improvements. Just get us the appropriate image for the background.

**Comment by rhnvrm** [comment]
@Sarthak-Mittal Please use some stock image for now, i'll ask the content team to send us images ASAP.

**Comment by rhnvrm** [comment]
@Sarthak-Mittal: https://www.flickr.com/photos/kondapivskrishnaprasanth choose from this.

**Comment by Sarthak-Mittal** [comment]
![24857866702_d251d81aea_o](https://cloud.githubusercontent.com/assets/15452197/16541893/276ef2f8-40b0-11e6-84e3-f21ef1e56880.jpg)

@rhnvrm How about this one? Or something else.

**Comment by rhnvrm** [comment]
@Sarthak-Mittal it seems nice :+1:

**Comment by ghost** [comment]
@rhnvrm +1
@Sarthak-Mittal The pic seems good :)
