### ISSUE TITLE
Improve Theme Video section and Fix 

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#22]
- The theme video section currently does not autoplay.
- Find some way to play the Video only when it gets visible on the screen. 
- Also don't play video automatically on mobile.
- Fix the arrows that lead to next section
- Add theme section to hamburger menu.

**Comment by FlameFractal** [comment]
Check on https://flamefractal.github.io/breeze-website/ and tell me if something needs to be changed regarding the theme section, before i send a PR. 
Video autoplay works as required. Check on phone by clicking Theme from hamburger menu. I've kept the mobile media query @768px. Tell me if you want it to be decrease/increased.

Also, I have raised an issue regarding the padding problem. Till it is solved, I have used **inline padding** in theme <section>. Hope we remove that at a later time.

**Comment by ghost** [comment]
@FlameFractal Nice work with the video autoplay :)

**Comment by FlameFractal** [comment]
@harshitbudhraja yo, thanks. media queries ftw!

**Comment by mr-karan** [comment]
http://tympanus.net/Tutorials/VideoOpeningAnimation/

^ See this and decide do we want something of this sorts ? :D Btw I like the present more, just sharing an alternative.

**Comment by rhnvrm** [comment]
LGTM :+1:

**Comment by rhnvrm** [comment]
@FlameFractal The video starts playing even if I click on Previous performers. Look into scrollspy provided by the theme we have used `Scrollspy that highlights active page sections
`(http://startbootstrap.com/template-overviews/grayscale/) Also, we should lose the exclamation mark in the menu and have a h1 tag inside it's section. It's also missing a scroll arrow and the scroll arrow above it points to contact section. 

You can also reduce the padding from 250px to 100px in grayscale:233 resolving #28 

Also, fix the height of the carousel. 

Also since you have not sent a PR yet, pull the changes from upstream and resolve the merge conflicts and check if any new changes cause any new bugs.

**Comment by rhnvrm** [comment]
#
