### ISSUE TITLE
Remove content-section class from <sections> 

### ISSUE THREAD

**Issue by FlameFractal** [rhnvrm/breeze-website#28]
Content-section class adds too much of padding which isn't looking good. 
Eg. when you click section names from the hamburger menu, they appear too far down and do not fit the page. 

PFA screenshot when clicked "About Us". The arrows for the next section should preferably appear within this page.

![screen shot 2016-07-03 at 11 25 44 am](https://cloud.githubusercontent.com/assets/9962648/16544193/6c8be35a-4119-11e6-82af-80979ffaa0f5.png)

**Comment by ghost** [comment]
@FlameFractal , I think there's no need for arrows above all sections...Doesn't look so good that way :)
Instead what I suggest is-
- Having a down-scroll on the first section and
- Having an up-scroll on the last section
  That's it...

That would be pretty decent ! What say @rhnvrm @mr-karan @arafsheikh ?

**Comment by rhnvrm** [comment]
rather than removing the class, change grayscale.css line 233 to 100px padding. Without padding it looks bad.

**Comment by FlameFractal** [comment]
Dammit. I'm so stupid.
I added 100vh to all the sections, so now all take up the entire screen and are well visible 👀 
Can close this issue now. I will send a PR as soon as i fix the other issues, and merge some conflicts.
