### ISSUE TITLE
Use the New Logo

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#5]
Instead of `Breeze '16` written, use the logo provided below instead.
Transparent white:
![logo-white-png-high-res](https://cloud.githubusercontent.com/assets/952036/16532875/6afe6044-3ff2-11e6-86e7-c2e8a627dc8d.png)
Black:
![logo-black-png](https://cloud.githubusercontent.com/assets/952036/16532886/7823b3fa-3ff2-11e6-8f9e-38d21b704bc5.png)
Teal:
![logo-png-hd](https://cloud.githubusercontent.com/assets/952036/16532887/791b94e4-3ff2-11e6-826a-f63696af1cc3.png)

Test whichever looks the best.

**Comment by ghost** [comment]
Well, the black logo makes it look somewhat dull, I feel.
Using the transparent teal logo, reflects the filter effects too...
![screenshot from 2016-07-02 15-31-31](https://cloud.githubusercontent.com/assets/16652667/16539764/3e3cfc50-406a-11e6-8135-575bd6c9ed4f.png)

**Comment by rhnvrm** [comment]
Done in #30
