### ISSUE TITLE
Update the background photo img/breeze.jpg

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/breeze-website#6]
- This photo is ~4 MB. Rerender it in photoshop for web so that it is of acceptable size by web standards.
- Remove `GROG Events` written on top and `Copyright Krishna Prasanth`.
- Bonus :cake: for making the image better in any way you feel would look great.

**Comment by mr-karan** [comment]
- I found an interesting property recently while working in CSS. `background blend mode`

```
.imageDiv {
  background-image:
    linear-gradient(
    rgba(255, 0, 0, 0.5),
    rgba(255, 0, 0, 0.5)
    ),
   background: url(“images/img.png”);
}
```

Play around with the values to get an interesting color wash effect.

**Comment by rhnvrm** [comment]
@harshitbudhraja - please look into what @mr-karan has suggested as well

**Comment by ghost** [comment]
Sure, I will :)
